---
title: "data_exploration"
author: "Josh Marvald"
date: "10/25/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

```


```{r message=FALSE, warning=FALSE}
train <- read_csv("data/train_2021.csv")
train <- na.omit(train)

# get rid of claim_number, claim_date, channel, vehicle_color, vehicle_category


```



```{r}
# indicator vars
train <- 
  train %>%
  mutate(Gender = ifelse(gender == "M", 1, 0))
```


```{r}
# any asoociations?

# married or not
train %>%
  group_by(marital_status) %>%
  summarise(fraud_perc = mean(fraud))
# looks like there is some association

# male or female
train %>%
  group_by(gender) %>%
  summarise(fraud_perc = mean(fraud))

# age
train %>%
  mutate(age = case_when(
    age_of_driver >= 50 ~ 1,
    age_of_driver < 50 ~ 0)) %>%
  group_by(age) %>%
  summarise(fraud_perc = mean(fraud))
# looks like 50 gives biggest diff

train %>%
  mutate(income = case_when(
    annual_income >= 25000 ~ 1,
    annual_income < 25000 ~ 0)) %>%
  group_by(income) %>%
  summarise(fraud_perc = mean(fraud))
```


```{r}
# weight training data more heavily for fraud cases
fraud_cases <- 
  train %>%
  filter(fraud == 1)

no_fraud <- 
  train %>%
  filter(fraud == 0)

set.seed(123)
fraud_sample <-
  sample(fraud_cases$claim_number, size = 1500)

no_fraud_sample <-
  sample(no_fraud$claim_number, size = 1500)

weighted_train <-
  train %>%
  filter(claim_number %in% fraud_sample | claim_number %in% no_fraud_sample)
```


```{r}
# best glm attempts
# subset <-
#   weighted_train %>%
#   mutate(age = case_when(
#     age_of_driver >= 50 ~ 1,
#     age_of_driver < 50 ~ 0
#   )) %>%
#   select(age, Gender, marital_status, high_education_ind, witness_present_ind, fraud) 
# 
# subset$age <- as.logical(subset$age)
# subset$Gender <- as.logical(subset$Gender)
# subset$marital_status <- as.logical(subset$marital_status)
# subset$high_education_ind <- as.logical(subset$high_education_ind)
# subset$witness_present_ind <- as.logical(subset$witness_present_ind)
# subset$fraud <- as.logical(subset$fraud)
# 
# 
# # prep
# for_best_logistic <- within(subset, {
#     age        
#     Gender
#     marital_status 
#     high_education_ind 
#     witness_present_ind
#     y <- fraud        
#     fraud  <- NULL        
# })


# res.best.logistic <-
#     bestglm(Xy = for_best_logistic,
#             family = binomial,
#             IC = "AIC",
#             method = "exhaustive")


# still cant figure out the form of paramters for bestglm()

```



```{r}
subset <-
  train %>%
  select(marital_status, safty_rating, annual_income, high_education_ind,
         witness_present_ind, policy_report_filed_ind, address_change_ind, past_num_of_claims,
         liab_prct, age_of_vehicle, vehicle_category, Gender, claim_est_payout,
         channel, accident_site, claim_day_of_week, living_status, age_of_driver) %>%
  mutate(day = case_when(
    claim_day_of_week == "Sunday" ~ 0,
    claim_day_of_week == "Monday" ~ 1,
    claim_day_of_week == "Tuesday" ~ 2,
    claim_day_of_week == "Wednesday" ~ 3,
    claim_day_of_week == "Thursday" ~ 4,
    claim_day_of_week == "Friday" ~ 5,
    claim_day_of_week == "Saturday" ~ 6
  )) %>%
  mutate(rent_own = case_when(
    living_status == "Own" ~ 1,
    living_status == "Rent" ~ 0
  )) %>%
  mutate(site = case_when(
    accident_site == "Highway" ~ 0,
    accident_site == "Parking Lot" ~ 1,
    accident_site == "Local" ~ 2
  )) %>%
  mutate(car_size = case_when(
    vehicle_category == "Compact" ~ 0,
    vehicle_category == "Medium" ~ 1,
    vehicle_category == "Large" ~ 2
  )) %>%
  mutate(method = case_when(
    channel == "Broker" ~ 0,
    channel == "Phone" ~ 1,
    channel == "Online" ~ 2
  )) %>%
  select(marital_status, safty_rating, annual_income, high_education_ind,
         witness_present_ind, policy_report_filed_ind, address_change_ind, past_num_of_claims,
         liab_prct, age_of_vehicle, car_size, Gender, claim_est_payout,
         method, site, day, rent_own, age_of_driver)

corr <- cor(subset)
corrplot::corrplot(corr)
```



